NDefines.NAI.AIR_WING_REINFORCEMENT_LIMIT = 40					-- How many flying wings AI will have in one group.
NDefines.NAI.AREA_DEFENSE_BASE_IMPORTANCE = 10					-- Area defense order base importance value (used for determining order of troop selections)
NDefines.NAI.AREA_DEFENSE_CIVIL_WAR_IMPORTANCE = 5				-- Area defense order importance value when a country is in a civil war as target or revolter.
NDefines.NAI.ATTACK_HEAVILY_DEFENDED_LIMIT = 0.2				-- AI will not launch attacks against heavily defended fronts unless they consider to have this level of advantage (1.0 = 100%)
NDefines.NAI.COMBINED_ARMS_LEVEL = 2						-- 0 = Never, 1 = Infantry/Artillery, 2 = Go wild
NDefines.NAI.CONVOY_NEED_SAFETY_BUFFER = 1.50					-- AI will try and keep 15% more convoys than what it needs.
NDefines.NAI.ENEMY_NAVY_STRENGTH_DONT_BOTHER = 1.5				-- If the enemy has a navy at least these many times stronger that the own, don't bother invading
NDefines.NAI.FRONT_UNITS_CAP_FACTOR = 18.0					-- A factor applied to total front size and supply use. Primarily effects small fronts
NDefines.NAI.HOUR_BAD_COMBAT_REEVALUATE = 12					-- if we are in combat for this amount and it goes shitty then try skipping it 
NDefines.NAI.MAX_DIST_PORT_RUSH = 500.0						-- If a unit is in enemy territory with no supply it will consider nearby ports within this distance.
NDefines.NAI.MAX_SUPPLY_DIVISOR = 5.0						-- To make sure the AI does not overdeploy divisions. Higher number means more supply per unit.
NDefines.NAI.MICRO_POCKET_SIZE = 10						-- Pockets with a size equal to or lower than this will be mocroed by the AI, for efficiency.
NDefines.NAI.MIN_FIELD_STRENGTH_TO_BUILD_UNITS = 0.9				-- Cancel unit production if below this to get resources out to units in the field
NDefines.NAI.MIN_MANPOWER_TO_BUILD_UNITS = 0.9					-- Cancel unit production if below this to get resources out to units in the field
NDefines.NAI.NAVAL_MAX_PRIO_THEATRES = 4					-- A nation may have a large number of theatres, but all of them having stationed/assigned navy is redundant
NDefines.NAI.NAVAL_MISSION_MIN_FLEET_SIZE = 4					-- AI will not send too small fleets on missions. Ignored if total number of ships country has is below	this.
NDefines.NAI.NAVY_PREFERED_MAX_SIZE = 40					-- AI will generally attempt to merge fleets into this size, but as a soft limit.
NDefines.NAI.ORG_UNIT_WEAK = 0.5						-- Organization % for unit to be considered weak
NDefines.NAI.PLAN_ACTIVATION_PLAYER_WEIGHT_FACTOR = 1.0				-- AI countries will hold on activating plans if player controlled countries have plans in the same location. Majors count extra (value of 1 will negate this)
NDefines.NAI.PLAN_ATTACK_DEPTH_FACTOR = 1.0					-- Factor applied to size or enemy being attacked.
NDefines.NAI.PLAN_ATTACK_MIN_ORG_FACTOR_HIGH = 0.6				
NDefines.NAI.PLAN_ATTACK_MIN_ORG_FACTOR_LOW = 0.9				-- Minimum org % for a unit to actively attack an enemy unit when executing a plan
NDefines.NAI.PLAN_ATTACK_MIN_ORG_FACTOR_MED = 0.75				-- (LOW,MED,HIGH) corresponds to the plan execution agressiveness level.
NDefines.NAI.PLAN_ATTACK_MIN_STRENGTH_FACTOR_HIGH = 0.6		
NDefines.NAI.PLAN_ATTACK_MIN_STRENGTH_FACTOR_LOW = 0.9				-- Minimum strength for a unit to actively attack an enemy unit when executing a plan
NDefines.NAI.PLAN_ATTACK_MIN_STRENGTH_FACTOR_MED = 0.75			
NDefines.NAI.PLAN_FRONT_SECTION_MIN_LENGTH = 9					-- When two front sections together are this short they will be merged for the AI
NDefines.NAI.PLAN_STEP_COST_LIMIT = 15						-- When stepping to draw a plan this cost makes it break if it hits hard terrain (multiplied by number of desired steps)
NDefines.NAI.POCKET_DISTANCE_MAX = 80000					-- shortest square distance we bother about chasing pockets
NDefines.NAI.REDEPLOY_DISTANCE_VS_ORDER_SIZE = 0.5				-- Factor applied to the path length of a unit compared to length of an order to determine if it should use strategic redeployment
NDefines.NAI.REGION_THREAT_PER_SUNK_CONVOY = 10					-- Threat value per convoy sunk in a region. Decays over time.
NDefines.NAI.RESERVE_TO_COMMITTED_BALANCE = 0.3					-- How many reserves compared to number of committed divisions in a combat (1.0 = as many as reserves as committed)
NDefines.NAI.SCARY_LEVEL_AVERAGE_DEFENSE = -0.3                			-- average front defense modifier to make it consider it as a PITA to go for
NDefines.NAI.SEND_VOLUNTEER_EVAL_CONTAINMENT_FACTOR = 0				-- How much AI containment factors into its evaluation of sending volunteers.
NDefines.NAI.SEND_VOLUNTEER_EVAL_MAJOER_POWER = 0			 	-- How willing major powers are to send volunteers.
NDefines.NAI.START_TRAINING_EQUIPMENT_LEVEL = 0.2				-- ai will not start to train if equipment drops below this level
NDefines.NAI.STOP_TRAINING_EQUIPMENT_LEVEL = 0.1				-- ai will not train if equipment drops below this level
NDefines.NAI.STRATEGIC_BOMBING_DEFENCE_IMPORTANCE = 1000.0
NDefines.NAI.STR_UNIT_STRONG = 0.9						-- Strength (equipment) % for unit to be considered strong
NDefines.NAI.STR_UNIT_WEAK = 0.6						-- Strength (equipment) % for unit to be considered weak
NDefines.NAI.SUPPLY_CRISIS_LIMIT = 0						-- If a unit is standing in an area with 
NDefines.NAI.TRADEABLE_FACTORIES_FRACTION = 1.0					-- Will at most trade away this fraction of factories.
NDefines.NAI.TRANSPORTS_PER_PARATROOPER = 3					-- Air transports only duty is to drop paratroopers.
NDefines.NAI.UNIT_ASSIGNMENT_TERRAIN_IMPORTANCE = 20.0				-- Terrain score for units are multiplied by this when the AI is deciding which front they should be assigned to
NDefines.NAI.UPGRADE_PERCENTAGE_OF_FORCES = 0.5					-- How big part of the army that should be considered for upgrading
NDefines.NAI.VP_GARRISON_VALUE_FACTOR = 1.0					-- Extent to which VP garrisons are prioritized, based on VP value and compared to other priority values.
NDefines.NAI.VP_LEVEL_IMPORTANCE_HIGH = 20					-- Victory points with values higher than or equal to this are considered to be of high importance.
NDefines.NAI.WANTED_UNITS_INDUSTRY_FACTORY = 5.0 				-- How many units a country wants is partially based on how much military industry that is available
NDefines.NCountry.CONVOY_RANGE_FACTOR = 0.5                  			-- how much range affects convoy need
NDefines.NCountry.RESOURCE_LENDLEASE_PRIORITY = 0.8				-- Default convoy priority for export lend lease
NDefines.NCountry.RESOURCE_ORIGIN_PRIORITY = 0.5				-- Default convoy priority for resources shipped internally
NDefines.NMilitary.BASE_DIVISION_BRIGADE_CHANGE_COST = 1			--Base cost to change a regiment column.
NDefines.NMilitary.BASE_DIVISION_BRIGADE_GROUP_COST = 1				--Base cost to unlock a regiment slot,
NDefines.NMilitary.BASE_DIVISION_SUPPORT_SLOT_COST = 1				--Base cost to unlock a support slot
NDefines.NMilitary.FRONT_MIN_PATH_TO_REDEPLOY = 1				-- If a units path is at least this long to reach its front location, it will strategically redeploy.
NDefines.NMilitary.PLAN_AREA_DEFENSE_COASTAL_FORT_IMPORTANCE = 10.0		-- Used when calculating the calue of defense area provinces for the battle plan system
NDefines.NMilitary.PLAN_EXECUTE_RUSH = 0					-- When looking for an attach target, this score limit is required in the battle plan to consider province for attack
NDefines.NMilitary.PLAN_MIN_AUTOMATED_EMPTY_POCKET_SIZE = 4			-- The battle plan system will only automatically attack provinces in pockets that has no resistance and are no bigger than these many provinces
NDefines.NMilitary.PLAN_PORVINCE_PORT_BASE_IMPORTANCE = 30.0			-- Added importance for area defense province with a port
NDefines.NMilitary.PLAN_PORVINCE_PORT_LEVEL_FACTOR = 3.0			-- Bonus factor for port level
NDefines.NMilitary.PLAN_PORVINCE_RESISTANCE_BASE_IMPORTANCE = 50.0		-- Used when calculating the calue of defense area provinces for the battle plan system (factored by resistance level)
NDefines.NMilitary.PLAN_PROVINCE_MEDIUM_VP_IMPORTANCE_AREA = 20.0		-- Used when calculating the calue of defense area in the battle plan system
NDefines.NMilitary.PLAN_SPREAD_ATTACK_WEIGHT = 8.0				-- The higher the value, the less it should crowd provinces with multiple attacks.
NDefines.NMilitary.PLAN_SUPPLY_FACTOR = 1.0					-- Factor applied to available supply on a front location when determining priority
NDefines.NMilitary.STRATEGIC_REDEPLOY_ORG_RATIO = 0.5				-- Ratio of max org while strategic redeployment
NDefines.NMilitary.SUPPLY_GRACE = 168						-- troops always carry 3 days of food and supply
